name: PharmaTrack CI/CD Pipeline

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  # --- BACKEND (Spring Boot) ---
  backend-build:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./BackEnd

    steps:
      - name: Récupération du code
        uses: actions/checkout@v4

      - name: Configuration de Java 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: maven

      - name: Donner les droits d'exécution au script Maven
        run: chmod +x mvnw

      - name: Build et Tests avec Maven

        run: ./mvnw clean verify

  # --- FRONTEND (Angular) ---
  frontend-build:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./FrontEnd

    steps:
      - name: Récupération du code
        uses: actions/checkout@v4

      - name: Configuration de Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'
          cache: 'npm'
          cache-dependency-path: FrontEnd/package-lock.json

      - name: Installation des dépendances

        run: npm ci

      - name: Build Angular

        run: npm run build -- --configuration production